version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: alter_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - alter_db:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis-container
    restart: unless-stopped
    ports:
      - "6380:6379"


  app:
    build: .
    restart: unless-stopped
    container_name: alter_api_server
    depends_on:
      - postgres
      - redis
      - zk
      - zoonavigator
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=redis

volumes:
  alter_db:
