version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: alter_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - alter_db:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis
    container_name: redis-container
    restart: unless-stopped
    ports:
      - "6380:6379"


  app:
    build: .
    restart: unless-stopped
    container_name: alter_api_server
    depends_on:
      - postgres
      - redis
    ports:
      - "3001:3001"
    env_file:
      - .env


volumes:
  alter_db:
